language: bash
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y optipng
script:
  - make
  - sudo chgrp 1000 -R .
  - make test
  - make clean
  - make verify-clean
sudo: required
services:
  - docker
