version: '3.2'
services:

  acceptance_tests:
    image: gradle:jdk8
    depends_on:
      - ftpd
      - selenium
    volumes:
      - type: bind
        source: .
        target: /home/gradle/project
    working_dir: /home/gradle/project

  ftpd:
    image: stilliard/pure-ftpd
    volumes:
      - ./pure-ftpd:/etc/pure-ftpd/passwd

  selenium:
    image: selenium/standalone-firefox-debug:3.9.1
    ports:
      - "5900:5900"
    volumes:
      - /dev/shm:/dev/shm
      - .:/project
