version: '3'
services:

  acceptance_tests:
    build:
      context: .
      dockerfile: python/Dockerfile
    depends_on:
      - ftpd
      - selenium
    volumes:
      - ./test/acceptance:/screenshots

  ftpd:
    image: stilliard/pure-ftpd
    volumes:
      - ./pure-ftpd:/etc/pure-ftpd/passwd

  selenium:
    image: selenium/standalone-firefox:3.9.1
    ports:
      - "4444"
    volumes:
      - /dev/shm:/dev/shm
      - .:/project
